### ISSUE TITLE
docker-compose up is not working

### ISSUE THREAD

**Issue by ajaysingh77** [dotnet-architecture/eShopOnDapr#67] opened 2021-12-08 10:41 UTC
while running the application with docker-compose up, it's not working. I tried with dapr version defined in the docker-compose file and also with the latest dapr version. every time following 3 containers are not spinning up with the following error.

Environment: Windows 11, Docker Desktop 4.2

Containers
1. eshopondapr_ordering-api_1
2. eshopondapr_identity-api_1
3. eshopondapr_catalog-api_1

Error:
`Unhandled exception. Dapr.DaprException: Bulk secret operation failed: the Dapr endpoint indicated a failure. See InnerException for details.

 ---> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: Connection refused (127.0.0.1:50001) SocketException: Connection refused", DebugException="System.Net.Http.HttpRequestException: Connection refused (127.0.0.1:50001)

 ---> System.Net.Sockets.SocketException (111): Connection refused

   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)

   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)

   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)

   --- End of inner exception stack trace ---

   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage request)

   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)

   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")

   at Dapr.Client.DaprClientGrpc.GetBulkSecretAsync(String storeName, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)

   --- End of inner exception stack trace ---

   at Dapr.Client.DaprClientGrpc.GetBulkSecretAsync(String storeName, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)

   at Dapr.Extensions.Configuration.DaprSecretStore.DaprSecretStoreConfigurationProvider.LoadAsync()

   at Dapr.Extensions.Configuration.DaprSecretStore.DaprSecretStoreConfigurationProvider.Load()

   at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)

   at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)

   at Dapr.Extensions.Configuration.DaprSecretStoreConfigurationExtensions.AddDaprSecretStore(IConfigurationBuilder configurationBuilder, String store, DaprClient client, IReadOnlyDictionary`2 metadata)

   at Microsoft.eShopOnDapr.Services.Catalog.API.ProgramExtensions.AddCustomConfiguration(WebApplicationBuilder builder) in /src/src/Services/Catalog/Catalog.API/ProgramExtensions.cs:line 12

   at Program.<Main>$(String[] args) in /src/src/Services/Catalog/Catalog.API/Program.cs:line 4`

**Comment by mgnoonan** [comment] 2021-12-08 13:01
I am experiencing the same issue.

**Comment by amolenk** [comment] 2021-12-08 14:02
Those containers are all trying to get a DB connection string from the secret store, which obviously doesn't work right now :-( I'll have a closer look later today

**Comment by amolenk** [comment] 2021-12-08 16:44
I just got a fresh clone of the main branch and ran the solution using Docker Compose, but cannot reproduce the problem. Can you share the logging of the Dapr sidecar of one of the services that fails?

**Comment by ajaysingh77** [comment] 2021-12-08 19:31
**Log from Order Api Dapr sidecar**

```
time="2021-12-08T19:27:02.3106295Z" level=info msg="starting Dapr Runtime -- version 1.4.0 -- commit ed969edc72b3934fffb481f079b736f3588e373a" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:02.3108314Z" level=info msg="log level set to: debug" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:02.3303132Z" level=info msg="metrics server started on :9090/" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.metrics type=log ver=1.4.0

time="2021-12-08T19:27:02.4401643Z" level=info msg="standalone mode configured" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:02.4404632Z" level=info msg="app id: ordering-api" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:02.4422904Z" level=info msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:02.448823Z" level=info msg="local service entry announced: ordering-api -> 172.22.0.13:32979" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.contrib type=log ver=1.4.0

time="2021-12-08T19:27:02.4489624Z" level=info msg="Initialized name resolution to mdns" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:02.4493879Z" level=info msg="loading components" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:02.7115689Z" level=debug msg="found component. name: sendmail, type: bindings.smtp/v1" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:02.7116797Z" level=debug msg="found component. name: pubsub, type: pubsub.rabbitmq/v1" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:02.7117298Z" level=debug msg="found component. name: eshop-secretstore, type: secretstores.local.file/v1" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:02.7117731Z" level=debug msg="found component. name: eshop-statestore, type: state.redis/v1" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:02.7120923Z" level=debug msg="loading component. name: sendmail, type: bindings.smtp/v1" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:02.7121601Z" level=warning msg="component sendmail references a secret store that isn't loaded: eshop-secretstore" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:02.7123622Z" level=debug msg="loading component. name: pubsub, type: pubsub.rabbitmq/v1" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:02.7378556Z" level=info msg="component loaded. name: pubsub, type: pubsub.rabbitmq/v1" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:02.7380885Z" level=debug msg="loading component. name: eshop-secretstore, type: secretstores.local.file/v1" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:02.8434378Z" level=info msg="component loaded. name: eshop-secretstore, type: secretstores.local.file/v1" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:02.8436746Z" level=debug msg="loading component. name: sendmail, type: bindings.smtp/v1" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:02.8439311Z" level=warning msg="smtp binding warn: User and password are empty" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.contrib type=log ver=1.4.0

time="2021-12-08T19:27:02.8440727Z" level=debug msg="smtp binding: using server :0" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.contrib type=log ver=1.4.0

time="2021-12-08T19:27:02.8441143Z" level=warning msg="smtp binding warning: Skip TLS Verification is enabled. This is insecure and is NOT recommended for production scenarios." app_id=ordering-api instance=2df5d99d66c6 scope=dapr.contrib type=log ver=1.4.0

time="2021-12-08T19:27:02.8441633Z" level=info msg="successful init for output binding sendmail (bindings.smtp/v1)" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:02.8442892Z" level=info msg="component loaded. name: sendmail, type: bindings.smtp/v1" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:02.8443715Z" level=debug msg="loading component. name: eshop-statestore, type: state.redis/v1" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:02.8461503Z" level=info msg="waiting for all outstanding components to be processed" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:02.8776942Z" level=info msg="component loaded. name: eshop-statestore, type: state.redis/v1" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:02.877981Z" level=info msg="all outstanding components processed" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:02.8782374Z" level=info msg="enabled gRPC tracing middleware" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime.grpc.api type=log ver=1.4.0

time="2021-12-08T19:27:02.8783259Z" level=info msg="enabled gRPC metrics middleware" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime.grpc.api type=log ver=1.4.0

time="2021-12-08T19:27:02.8786151Z" level=info msg="API gRPC server is running on port 50001" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:02.8796113Z" level=info msg="enabled metrics http middleware" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime.http type=log ver=1.4.0

time="2021-12-08T19:27:02.8798101Z" level=info msg="enabled tracing http middleware" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime.http type=log ver=1.4.0

time="2021-12-08T19:27:02.8799792Z" level=info msg="http server is running on port 3500" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:02.8800306Z" level=info msg="The request body size parameter is: 4" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:02.8801461Z" level=info msg="enabled gRPC tracing middleware" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime.grpc.internal type=log ver=1.4.0

time="2021-12-08T19:27:02.8802197Z" level=info msg="enabled gRPC metrics middleware" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime.grpc.internal type=log ver=1.4.0

time="2021-12-08T19:27:02.8805093Z" level=info msg="internal gRPC server is running on port 32979" app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:02.8805794Z" level=info msg="application protocol: http. waiting on port 80.  This will block until the app is listening on that port." app_id=ordering-api instance=2df5d99d66c6 scope=dapr.runtime type=log ver=1.4.0

time="2021-12-08T19:27:32.4518524Z" level=debug msg="Refreshing all mDNS addresses." app_id=ordering-api instance=2df5d99d66c6 scope=dapr.contrib type=log ver=1.4.0

time="2021-12-08T19:27:32.451921Z" level=debug msg="no mDNS apps to refresh." app_id=ordering-api instance=2df5d99d66c6 scope=dapr.contrib type=log ver=1.4.0

time="2021-12-08T19:28:02.4623413Z" level=debug msg="Refreshing all mDNS addresses." app_id=ordering-api instance=2df5d99d66c6 scope=dapr.contrib type=log ver=1.4.0

time="2021-12-08T19:28:02.4625899Z" level=debug msg="no mDNS apps to refresh." app_id=ordering-api instance=2df5d99d66c6 scope=dapr.contrib type=log ver=1.4.0

time="2021-12-08T19:28:32.4629996Z" level=debug msg="Refreshing all mDNS addresses." app_id=ordering-api instance=2df5d99d66c6 scope=dapr.contrib type=log ver=1.4.0

time="2021-12-08T19:28:32.4632068Z" level=debug msg="no mDNS apps to refresh." app_id=ordering-api instance=2df5d99d66c6 scope=dapr.contrib type=log ver=1.4.0

time="2021-12-08T19:29:02.4636026Z" level=debug msg="Refreshing all mDNS addresses." app_id=ordering-api instance=2df5d99d66c6 scope=dapr.contrib type=log ver=1.4.0

time="2021-12-08T19:29:02.4636712Z" level=debug msg="no mDNS apps to refresh." app_id=ordering-api instance=2df5d99d66c6 scope=dapr.contrib type=log ver=1.4.0

time="2021-12-08T19:29:32.4642925Z" level=debug msg="Refreshing all mDNS addresses." app_id=ordering-api instance=2df5d99d66c6 scope=dapr.contrib type=log ver=1.4.0

time="2021-12-08T19:29:32.4643915Z" level=debug msg="no mDNS apps to refresh." app_id=ordering-api instance=2df5d99d66c6 scope=dapr.contrib type=log ver=1.4.0

time="2021-12-08T19:30:02.4651265Z" level=debug msg="Refreshing all mDNS addresses." app_id=ordering-api instance=2df5d99d66c6 scope=dapr.contrib type=log ver=1.4.0

time="2021-12-08T19:30:02.4651849Z" level=debug msg="no mDNS apps to refresh." app_id=ordering-api instance=2df5d99d66c6 scope=dapr.contrib type=log ver=1.4.0
```

**Comment by amolenk** [comment] 2021-12-09 08:21
Thanks, haven't found the actual issue yet, but I at least have a repro on one of my other machines.

**Comment by mgnoonan** [comment] 2021-12-09 16:31
#69 almost fixed everything for me, but the Catalog API is still failing with the secrets error.

**Comment by ajaysingh77** [comment] 2021-12-09 19:39
after applying #69 changes now sometimes order and identity api start running but catalog api is still failing everytime. 
seems there is an issue in dapr dotnet sdk 
https://github.com/dapr/dotnet-sdk/issues/779

**Comment by mgnoonan** [comment] 2021-12-09 20:35
@amolenk Related perhaps? 
https://github.com/dapr/dotnet-sdk/issues/779

**Comment by amolenk** [comment] 2021-12-10 08:16
FYI Just merged some workarounds for the current issues. Temporarily removed the use of `AddDaprSecretStore` and replaced RabbitMQ with Redis pubsub.

Solution should now work properly when started using Docker Compose.

**Comment by mgnoonan** [comment] 2021-12-10 17:41
Confirmed, it is working for me now. Thanks!

**Comment by ajaysingh77** [comment] 2021-12-11 14:20
@amolenk yes these temp workarounds resolve the issue for now. Thanks!
I also tried the retry functionality around "AddDaprSecretStore" codebase and that resolves at atleast following error `Unhandled exception. Dapr.DaprException: Bulk secret operation failed: the Dapr endpoint indicated a failure. See InnerException for details`
but this path requires more effort to test the overall functionality. Not sure whether it is worth putting effort here or waiting for dotnet-sdk issue to be fixed off.

**Comment by amolenk** [comment] 2022-05-31 15:35
Tracking the remaining work for enabling the Dapr configuration provider in #100

**Closed by amolenk** 2022-05-31 15:35 UTC
